Updates to DinD. Using Docker v1.0.1 in DinD

diff --git a/contrib/peas-dind/wrapdocker b/contrib/peas-dind/wrapdocker
--- a/contrib/peas-dind/wrapdocker
+++ b/contrib/peas-dind/wrapdocker
@@ -1,17 +1,16 @@
 #!/bin/bash
-exec 2>&1 # Redirect STDERR and STDOUT to STDOUT
 
 # First, make sure that cgroups are mounted correctly.
 CGROUP=/sys/fs/cgroup
 
 [ -d $CGROUP ] || 
-	mkdir $CGROUP
+    mkdir $CGROUP
 
 mountpoint -q $CGROUP || 
-	mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup $CGROUP || {
-		echo "Could not make a tmpfs mount. Did you use -privileged?"
-		exit 1
-	}
+    mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup $CGROUP || {
+        echo "Could not make a tmpfs mount. Did you use -privileged?"
+        exit 1
+    }
 
 if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security
 then
@@ -58,23 +57,23 @@ done
 # a "sub-container" properly if the "devices" cgroup is not in its
 # own hierarchy. Let's detect this and issue a warning.
 grep -q :devices: /proc/1/cgroup ||
-	echo "WARNING: the 'devices' cgroup should be in its own hierarchy."
+    echo "WARNING: the 'devices' cgroup should be in its own hierarchy."
 grep -qw devices /proc/1/cgroup ||
-	echo "WARNING: it looks like the 'devices' cgroup is not mounted."
+    echo "WARNING: it looks like the 'devices' cgroup is not mounted."
 
 # Now, close extraneous file descriptors.
 pushd /proc/self/fd >/dev/null
 for FD in *
 do
-	case "$FD" in
-	# Keep stdin/stdout/stderr
-	[012])
-		;;
-	# Nuke everything else
-	*)
-		eval exec "$FD>&-"
-		;;
-	esac
+    case "$FD" in
+    # Keep stdin/stdout/stderr
+    [012])
+        ;;
+    # Nuke everything else
+    *)
+        eval exec "$FD>&-"
+        ;;
+    esac
 done
 popd >/dev/null
 
@@ -82,7 +81,7 @@ popd >/dev/null
 # delete it so that docker can start.
 rm -rf /var/run/docker.pid
 
-docker -d &
+docker -d &>/var/log/docker.log &
 
 # Wait for Docker to be up and running
 while : ; do
@@ -97,8 +96,7 @@ fi
 
 export LANG="C.UTF-8"
 export LC_ALL="C.UTF-8"
-/usr/bin/mongod --smallfiles &
-cd /home/peas
+/usr/bin/mongod --smallfiles &>/var/log/mongo.log &
 
 # If /var/lib/gems is mounted as a volume, then the first time Peas boots, there will be no
 # bundler command, even though it was installed with the Dockerfile. So install it.
@@ -106,8 +104,10 @@ cd /home/peas
 if [ `ls -1A /var/lib/gems | wc -l` -eq 0 ]; then
     gem install bundler
 fi
-bundle install
-bundle exec foreman start -f ./Procfile &
+
+cd /home/peas/repo
+bundle install --binstubs /var/lib/gems/binstubs
+bundle exec /var/lib/gems/binstubs/foreman start -f ./Procfile &
 
 sleep 5
 exec bash
